### ISSUE TITLE
Look at batect to run container or tasks as user

### ISSUE THREAD

**Issue by maxhbr** [maxhbr/octrc#3]
https://batect.dev/docs/concepts/run-as-current-user-mode

**Comment by maxhbr** [comment]
looks like podman solves all issues and is the better choice. no need for batect

**Comment by sschuberth** [comment]
Mind sharing how to use *podman* to run as the current user (on Linux and Windows platforms) and to run ORT functional tests in a container?

**Comment by maxhbr** [comment]
Previously I ran commands like
<pre>
$ docker run -i --rm <b>-v /etc/group:/etc/group:ro -v /etc/passwd:/etc/passwd:ro -u $(id -u):$(id -g)</b> .....
</pre>
and that can simply be replaced by podman with
```
$ podman run -i --rm .....
```
and it behaves as expected. It is executed with the current user and behaves as expected. 

Only tern is not yet working with podman (but maybe that is also already outdated:  https://github.com/tern-tools/tern/issues/1087)

**Comment by sschuberth** [comment]
However, [the Podman service runs only on Linux platforms](https://podman.io/whatis.html).

**Comment by maxhbr** [comment]
no issue for me ;)
